apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
  # This pod tests the K3s built-in local-path-provisioner.
  # It mounts the PVC defined in pvc.yaml at /data.
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
